image: "python:3.7.9" 

before_script:
    - python --version
    - pip install -r requirements_editor.txt

stages:
    - deploy

build_app:
    stage: deploy
    script:
        - chmod 777 ./utilities/build_tools/*.spec 
        - chmod 777 ./utilities/build_tools/*.sh # Might be totally unneeded, but seemed to solve errors
        - ./utilities/build_tools/editor_build.sh
